/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"
#include "system_clock.h"
//#include"interrupt_PA0.h"
//#include "systick_delay.h"
#include "systick_interrupt.h"
//int interrupt_PA0 =0;
int main(void)
{
    config();
	init_GP(PC,13,OUT50,O_GP_PP);
//	init_GP(PA,0,IN,I_PP);
//	W_GP(PC, 13, LOW);
//	init_interrupt_PA0();
//	init_systick_delay();
	init_systick_interrupt(1000);



	while(1){

	}
}

